psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS product_categories;"
psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS products;"
psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS customers;"
psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS orders;"
psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS shopping_carts;"
psql -U alperentasdelen -d postgres -c "DROP TABLE IF EXISTS refunds;"
